### ISSUE TITLE
Set timer to hours

### ISSUE THREAD

**Issue by Rex-82** [S1mplyD/RecipeBotReborn#10]
Timer is currently in ms, set it to accept minimum 1 hour

**Comment by S1mplyD** [comment]
fixed in commit 3093c9d94c853fe8b1bdef45cae751c52c2881db

**Comment by Rex-82** [comment]
Debugging `/timer` command.
Adding better argument and error handling since currently users can set any amount grater than 1 and text (such as "a")

**Comment by Rex-82** [comment]
### timerCommand
- Added command permission check to be `ManageChannels` _(eg. Only Mods can see and use this command)_
- Set all interactions to `ephemeral: true` so that only the interacting user can see the response
- Fixed input argument check, now every variation of "off" and "on" works _(eg. Off, oFF, OFF, ecc.)_
- Added check for unwanted argument text handling _(eg. `/timer aaa`, `/timer vsvr`, ecc. now give an "error" response)._ 
Fixed in: 38467d8
<hr>

### src/../querys/timers
- Added time validation when `startAllTimer()` is called to check if the time value is within the 1-24 hour range _(adjusted to ms)_. 
Updates the timer to 1 hour if the time value is not valid.
Fixed in: 40eaaab
<hr>

### src/utils/timers
- Fixed Time value handling for `createTimer()` and `updateTimer()` functions to check if time is within the 1-24 hours range. Added Promises instead of "Error" to separate different errors
Fixed in: 01c5ac3
