### ISSUE TITLE
Check Workflow action error

### ISSUE THREAD

**Issue by Rex-82** [S1mplyD/RecipeBotReborn#11]
Action ruturns error:

```
/home/runner/work/RecipeBotReborn/RecipeBotReborn/node_modules/mongodb-connection-string-url/lib/index.js:86
            throw new MongoParseError('Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"');
                  ^

MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
```

**Comment by S1mplyD** [comment]
I think this issue is caused by the command "npm run deploy" that for some reasons it start the whole server instead of stopping after finishing its activities. 
I'm gonna check it now.

**Comment by S1mplyD** [comment]
After further testing I can say that the problem is cause by deployCommands.js not getting mongo url

**Comment by S1mplyD** [comment]
Adding mongo url to env variables in workflow file fixed the issue
